version: '2'
services:
  app-back:
    image: tacele/notes-demo:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=exampledb
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:9.6
    hostname: postgres
    #domainname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exampledb
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.163.252.0/16